from setupDongle import setup
import click

@click.command()
@click.option('--testnet', default=False, is_flag=True, help="If set, will set up the dongle in testnet mode." )
def main(testnet):
  print "This script is for setting up a new BTChip with a completely random seed, generated by the chip itself."
  setup(None, testnet)

if __name__ == "__main__":
  main()
